# Norma: Copyright 2025 National Technology & Engineering Solutions of
# Sandia, LLC (NTESS). Under the terms of Contract DE-NA0003525 with NTESS,
# the U.S. Government retains certain rights in this software. This software
# is released under the BSD license detailed in the file license.txt in the
# top-level Norma.jl directory.

using LinearAlgebra
using StaticArrays

@testset "Hencky Matrix Logarithm" begin
    # log_spd (inverse scaling and squaring, no eigendecomposition) against
    # LinearAlgebra's LAPACK-bound matrix logarithm, across the spectrum
    # regimes that matter: repeated eigenvalues, extreme conditioning, and a
    # generic C = F'F.  At the identity, the reference state of every
    # simulation, the result is exactly zero, with no branch on the spectrum.
    F = SMatrix{3,3,Float64,9}([1.2 0.3 0.0; 0.0 0.9 0.1; 0.05 0.0 1.1])
    cases = [
        SMatrix{3,3,Float64,9}(4.0 * I),
        SMatrix{3,3,Float64,9}(1.0e-8 * I),
        SMatrix{3,3,Float64,9}(Diagonal([1.0e4, 1.0, 1.0e-4])),
        SMatrix{3,3,Float64,9}(Diagonal([1.0e6, 1.0, 1.0e-6])),
        SMatrix{3,3,Float64,9}(Diagonal([1.0e-2, 1.0e-5, 1.0e-8])),
        F' * F,
    ]
    for C in cases
        L = Norma.log_spd(C)
        Lref = log(Matrix(0.5 * (C + C')))
        @test norm(Matrix(L) - Lref) < 1.0e-12 * max(1.0, norm(Lref))
    end
    @test all(Norma.log_spd(SMatrix{3,3,Float64,9}(I)) .== 0.0)

    # A non-positive-definite input aborts rather than returning garbage.
    Norma.NORMA_TEST_MODE[] = true
    try
        @test_throws Norma.NormaAbortException Norma.log_spd(SMatrix{3,3,Float64,9}(Diagonal([1.0, 1.0, -1.0])))
    finally
        Norma.NORMA_TEST_MODE[] = false
    end
end

@testset "Hencky Reference Values" begin
    # Energy and PK1 stress against the Hencky model in ConstitutiveModels
    # (Carina's material library), with E = 1, nu = 0.3.  The reference
    # values were generated by running that package directly, so this pins
    # the formulations to each other without a package dependency.
    material = Norma.Hencky(Norma.Parameters("elastic modulus" => 1.0, "Poisson's ratio" => 0.3, "density" => 1.0))
    @test material.κ ≈ 0.8333333333333334 rtol = 1.0e-14
    @test material.μ ≈ 0.38461538461538464 rtol = 1.0e-14
    references = [
        ([1.2 0.3 0.0; 0.0 0.9 0.1; 0.05 0.0 1.1], 0.046586868528389946,
         [0.1863954649391752 0.10235673995835214 0.0032290424224019508
          0.07590036661697895 0.004545100881274605 0.033672433417388965
          0.0037220258246121476 0.028017629740221085 0.15618828323777834]),
        ([2.5 0.0 0.0; 0.0 0.7 0.0; 0.0 0.0 0.85], 0.42749329216656246,
         [0.37357334636996636 0.0 0.0
          0.0 -0.06467285726428264 0.0
          0.0 0.0 0.12244680029905868]),
        ([1.001 0.002 0.0; 0.0 0.999 0.001; 0.0 0.0 1.0005], 1.8987634355244218e-6,
         [0.0010548343557319029 0.0007692307689105996 -3.839746792775321e-7
          0.0007686589899580042 -0.0004832473904762149 0.0003848082846476555
          -1.1524414232032123e-6 0.0003847135990046232 0.000671803384360677]),
    ]
    for (Fm, W_ref, P_ref) in references
        F = SMatrix{3,3,Float64,9}(Fm)
        W, P, _ = Norma.constitutive(material, F)
        @test W ≈ W_ref rtol = 1.0e-12
        @test norm(Matrix(P) - P_ref) < 1.0e-12 * norm(P_ref)
    end

    # The analytic stress is the gradient of the energy: check against the
    # AD primitives, which differentiate through log_spd with dual numbers.
    F = SMatrix{3,3,Float64,9}([1.2 0.3 0.0; 0.0 0.9 0.1; 0.05 0.0 1.1])
    W, P, AA = Norma.constitutive(material, F)
    W_ad, P_ad = Norma.stress_ad(material, F)
    @test W ≈ W_ad rtol = 1.0e-13
    @test norm(P - P_ad) < 1.0e-13
    # The AD tangent matches a central finite difference of the analytic P.
    h = 1.0e-6
    for k in 1:3, l in 1:3
        dF = zeros(3, 3)
        dF[k, l] = h
        P_plus = Norma.constitutive(material, F + SMatrix{3,3,Float64,9}(dF))[2]
        P_minus = Norma.constitutive(material, F - SMatrix{3,3,Float64,9}(dF))[2]
        AA_fd = Matrix(P_plus - P_minus) / (2.0 * h)
        @test maximum(abs.(Array(AA)[:, :, k, l] - AA_fd)) < 1.0e-6
    end
end

@testset "Single Static Solid Cube Hencky Uniaxial" begin
    # Uniaxial stress at stretch 2 on the standard cube: symmetry conditions
    # on the minus faces, prescribed axial displacement on nsz+, lateral plus
    # faces free.  The defining property of the Hencky model is that this has
    # a closed-form homogeneous solution at ANY stretch: lateral log stretch
    # is exactly -nu times the axial one, and Cauchy stress
    # sigma_zz = E log(lambda) / J with J = lambda^(1 - 2 nu).  Every other
    # finite-strain model in Norma only approaches these values as the
    # stretch shrinks; here they hold exactly at 100% strain.
    cp("../examples/single/static-solid/cube/standard/cube-hencky.yaml", "cube-hencky.yaml"; force=true)
    cp("../examples/single/static-solid/cube/standard/cube.g", "cube.g"; force=true)
    simulation = Norma.run("cube-hencky.yaml")
    integrator = simulation.integrator
    model = simulation.model
    rm("cube-hencky.yaml"; force=true)
    rm("cube.g"; force=true)
    rm("cube-hencky.e"; force=true)

    E = 1.0e9
    ν = 0.25
    λ = 2.0
    λ_lateral = λ^(-ν)
    J = λ^(1.0 - 2.0 * ν)
    σ_axial = E * log(λ) / J

    disp = integrator.displacement
    min_disp_x = minimum(disp[1:3:end])
    min_disp_y = minimum(disp[2:3:end])
    max_disp_z = maximum(disp[3:3:end])
    avg_stress = average_components(model.stress)

    @test max_disp_z ≈ 1.0 atol = 1.0e-12
    @test min_disp_x ≈ λ_lateral - 1.0 rtol = 1.0e-9
    @test min_disp_y ≈ λ_lateral - 1.0 rtol = 1.0e-9
    @test avg_stress[3] ≈ σ_axial rtol = 1.0e-9
    @test abs(avg_stress[1]) < 1.0e-4 * σ_axial
    @test abs(avg_stress[2]) < 1.0e-4 * σ_axial
    @test abs(avg_stress[4]) < 1.0e-4 * σ_axial
    @test abs(avg_stress[5]) < 1.0e-4 * σ_axial
    @test abs(avg_stress[6]) < 1.0e-4 * σ_axial
end
