name: Norma CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1.11']
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install torch
          pip install numpy
          pip install git+https://github.com/sandialabs/norma-opinf.git 
 
      - name: Cache Julia artifacts
        uses: julia-actions/cache@v2

      - name: Build project
        uses: julia-actions/julia-buildpkg@v1
        with:
          test_args: 'with-nnopinf'
        env:
          PYTHON: python

      - name: Run tests
        uses: julia-actions/julia-runtest@v1

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
